"""Phase 2 tables: zone_state, slot_state, camera_health, flow_event, correction (data-model.md §1)

Revision ID: 0001
Revises:
Create Date: 2026-10-08 21:05:00.771285

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "camera_health",
        sa.Column("camera_id", sa.String(), nullable=False),
        sa.Column("ts", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("issue", sa.String(), nullable=True),
        sa.Column("fps", sa.Float(), nullable=True),
        sa.Column("last_frame_age_s", sa.Float(), nullable=True),
        sa.Column("inference_ms_avg", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("camera_id"),
    )
    op.create_table(
        "correction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.String(length=32), nullable=False),
        sa.Column("zone_id", sa.String(), nullable=False),
        sa.Column("old_occupied", sa.Integer(), nullable=False),
        sa.Column("new_occupied", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "flow_event",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("ts", sa.String(length=32), nullable=False),
        sa.Column("camera_id", sa.String(), nullable=False),
        sa.Column("zone_id", sa.String(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    with op.batch_alter_table("flow_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_flow_event_ts"), ["ts"], unique=False)

    op.create_table(
        "slot_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.String(length=32), nullable=False),
        sa.Column("camera_id", sa.String(), nullable=False),
        sa.Column("slot_id", sa.String(), nullable=False),
        sa.Column("taken", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("slot_state", schema=None) as batch_op:
        batch_op.create_index("ix_slot_state_slot_id_ts", ["slot_id", "ts"], unique=False)

    op.create_table(
        "zone_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.String(length=32), nullable=False),
        sa.Column("zone_id", sa.String(), nullable=False),
        sa.Column("occupied", sa.Integer(), nullable=False),
        sa.Column("free", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("zone_state", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_zone_state_ts"), ["ts"], unique=False)
        batch_op.create_index("ix_zone_state_zone_id_ts", ["zone_id", "ts"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("zone_state", schema=None) as batch_op:
        batch_op.drop_index("ix_zone_state_zone_id_ts")
        batch_op.drop_index(batch_op.f("ix_zone_state_ts"))

    op.drop_table("zone_state")
    with op.batch_alter_table("slot_state", schema=None) as batch_op:
        batch_op.drop_index("ix_slot_state_slot_id_ts")

    op.drop_table("slot_state")
    with op.batch_alter_table("flow_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_flow_event_ts"))

    op.drop_table("flow_event")
    op.drop_table("correction")
    op.drop_table("camera_health")
    # ### end Alembic commands ###
